theme: jekyll-theme-midnight
title: UW MRO Focuser
description: Software to automate focusing the UW Manastash Ridge Observatory (henceforth MRO) telescope.
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - CONTRIBUTING.md
  - README.md
  - LICENSE.md
  - COPYING.md
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - ISSUE_TEMPLATE.md
  - PULL_REQUEST_TEMPLATE.md
